dataset:
  name: glove
  config:
    dim: 50
    max_vectors: 5000

model:
  name: dae
  config:
    latent_dim: 16
    reconstruction_loss: mse
    noise_type: gaussian
    noise_std: 0.1
    masking_ratio: 0.3
    apply_noise_in_eval: false

encoder:
  name: mlp
  config:
    hidden_dims: [64, 32]
    activation: relu
    use_bias: true

decoder:
  name: mlp
  config:
    hidden_dims: [64, 50]
    activation: relu
    use_bias: true

trainer:
  output_dir: artifacts/glove/dae
  validation_ratio: 0.1
  test_ratio: 0.1
  seed: 42
  epochs: ${epoch}$
  batch_size: 128
  learning_rate: 0.001
  device: auto
  show_only_best_epochs: true
  advice: false
